//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fruit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTable
    {
        public int userId { get; set; }
        public string userName { get; set; }
        public string userPwd { get; set; }
        public string userTel { get; set; }
        public string userEmail { get; set; }
        public string userSex { get; set; }
        public string userQQ { get; set; }
        public string userType { get; set; }
        public string userTime { get; set; }
        public string userRegTime { get; set; }
    }
}
